### ISSUE TITLE
Make scio-avro compile

### ISSUE THREAD

**Issue by MaximeKjaer** [scalacenter/scio#4]
Code introduced in d444b239c3c2be3df4c6bd002df98a44bc1eaf03 seems to have broken build of scio-avro on Scala 2.13.5

```
sbt:scio> scio-avro/compile 
[info] compiling 15 Scala sources to /home/maxime/code/scio/scio-avro/target/scala-2.13/classes ...
[error] /home/maxime/code/scio/scio-avro/src/main/scala/com/spotify/scio/avro/types/AvroType.scala:50:8: Companions 'trait AvroType' and 'object AvroType' must be defined in same file:
[error]   Found in /home/maxime/code/scio/scio-avro/src/main/scala-2/com/spotify/scio/avro/types/AvroTypeMacros.scala and /home/maxime/code/scio/scio-avro/src/main/scala/com/spotify/scio/avro/types/AvroType.scala
[error] object AvroType extends AvroTypeMacros {
[error]        ^
[error] /home/maxime/code/scio/scio-avro/src/main/scala/com/spotify/scio/avro/types/AvroType.scala:89:7: AvroType is already defined as trait AvroType
[error] class AvroType[T: TypeTag] extends Serializable {
[error]       ^
[error] two errors found
[error] (scio-avro / Compile / compileIncremental) Compilation failed
[error] Total time: 4 s, completed Mar 11, 2021 5:00:07 PM
```
